name: Generate HTML

on:
  push:
    paths:
      - 'Questions.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown
          pip install playwright
          playwright install
          playwright install-deps

      - name: Generate HTML
        run: python3 main.py index.html convert

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KaungPyaeHtet/CS-IGCSE.git
          git add index.html
          git commit -m "Auto-update index.html from Questions.md" || echo "No changes"
          git push